const v = 100;
const x = 200;
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
console.log('ahmed');
const d = 300;